version: '3'

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'dbReport'
      MYSQL_ROOT_PASSWORD: testPass123
      MYSQL_USER: testUser
      MYSQL_PASSWORD: testPass123
      MYSQL_ROOT_HOST: '%'
    volumes:
        - db-report:/var/lib/mysql
volumes:
  db-report: